blogs/urls.py
from django.urls import path, include

from .views import ListBlogsView, DetailBlogsView, blogs_filtrados

app_name = 'blogs'

urlpatterns = [
    path('blogs/',ListBlogsView.as_view(), name='blogs'),
   	path('blogs/<int:id>/<str:uri>/', DetailBlogsView, name='detalle-blog'),
    path('blogs/filtrar/', blogs_filtrados, name='blog-filtro'),

]


#  patterns('blogs.views',
#     url(r'^blogs/$', ListBlogsView.as_view(), name='blogs'),
#     url(r'^blogs/(?P<id>[0-9]+)/(?P<uri>[-_\w]+)/$', 'DetailBlogsView', 
#     									name='detalle-blog'),
#     url(r'^blogs/filtrar/$', 'blogs_filtrados', name='blog-filtro'),

# )

noticias/urls.py
from django.urls import path
from .views import HomePageView, ListNewsView, DetailNewsView, HistoriaPageView, QuienesPageView, ContactenosPageView, ListServiceView, ListPortfolioView

app_name = 'noticias'

urlpatterns =   [
    path('', HomePageView.as_view(), name = "home"),
    path('portafolio/servicios/', ListServiceView.as_view(), name = "servicios"),
    path('portafolio/sistemas/', ListPortfolioView.as_view(), name = "portafolio1"),
    path('historia-simas/', HistoriaPageView.as_view(), name = "historia"),
    path('quienes-somos/', QuienesPageView.as_view(), name = "somos"),
    path('noticias/', ListNewsView.as_view(), name = "noticias"),
   	path('noticias/<int:id>/<str:uri>/', DetailNewsView, name = "detalle-noticia"),
    path('contactenos/', ContactenosPageView.as_view(), name = "contactenos"),
]

publicaciones/urls.py
from django.urls import path, include
from .views import ListBooksView, DetailBooksView, ListBookSimasView, ListBookCidocView

app_name = 'publicaciones'

urlpatterns = [
    path('publicaciones/', ListBooksView.as_view(), name ='publicaciones'),
    path('publicaciones/<int:id>/<str:uri>/', DetailBooksView, name ='detalle-publicacion'),
    path('publicaciones/simas/', ListBookSimasView.as_view(), name ='publicaciones'),
    path('publicaciones/cidoc/', ListBookCidocView.as_view(), name ='publicaciones'),
]



""" urlpatterns = patterns(
    'publicaciones.views',
    url(r'^publicaciones/$', ListBooksView.as_view(),
        name='publicaciones'),
    url(r'^publicaciones/(?P<id>[0-9]+)/(?P<uri>[-\w]+)/$',
        'DetailBooksView', name='detalle-publicacion'),
    url(r'^publicaciones/simas/$', ListBookSimasView.as_view(),
        name='publicaciones'),
    url(r'^publicaciones/cidoc/$', ListBookCidocView.as_view(),
        name='publicaciones'),
)
 """

websimas/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from noticias.views import contacto_ajax

urlpatterns = [

    path('', include(('publicaciones.urls','publicaciones'), namespace='publicaciones')),
    path('', include(('noticias.urls','noticias'), namespace='noticias')),
    path('', include(('blogs.urls','blogs'), namespace='blogs')),
    path('busqueda/', include(('googlesearch.urls','googlesearch'), namespace='googlesearch')),    
    path('contacto_ajax/', contacto_ajax, name='contacto_ajax'),
    path('admin/', admin.site.urls),
    path('captcha/', include('captcha.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),

]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL , document_root = settings.STATIC_ROOT )
    urlpatterns += static(settings.MEDIA_URL , document_root = settings.MEDIA_ROOT )

contacto/models.py
from django.db import models
from ckeditor.fields import RichTextField

# Create your models here.

class Contacto(models.Model):
	texto = RichTextField()

	def __str__(self):
		return "Contacto"
		

historia/models.py
# -*- coding: utf-8 -*-
from django.db import models
from ckeditor.fields import RichTextField
from websimas.utils import get_file_path
from sorl.thumbnail import ImageField

# Create your models here.

class Historias(models.Model):
    fecha = models.DateField('Fecha de la historia')
    titulo = models.CharField(max_length=250)
    descripcion = models.TextField(blank=True, null=True)
    foto = ImageField(upload_to=get_file_path,blank=True, null=True)

    fileDir = 'fotosHistoria/'

    class Meta:
        verbose_name_plural = "Historia de simas"

    def __str__(self):
        return self.titulo

portafolio/models.py
# -*- coding: utf-8 -*-
from django.db import models
from fotos.models import *
from django.contrib.contenttypes.fields import GenericRelation

# Create your models here.
class Organizaciones(models.Model):
    nombre = models.CharField(max_length=250)
    iniciales = models.CharField(max_length=150)

    def __str__(self):
        return self.iniciales

class Portafolio(models.Model):
    servicio = models.CharField('Nombre del servicio', max_length=250)
    resumen = models.TextField()
    fecha = models.DateField('Fecha de realización')
    link = models.URLField(blank=True)
    organizacion = models.ManyToManyField(Organizaciones)

    fotos = GenericRelation(Fotos)

    def __str__(self):
        return self.servicio

contacto/views.py
from django.shortcuts import render

# Create your views here.

historia/views.py
from django.shortcuts import render

# Create your views here.

portafolio/views.py
from django.shortcuts import render

# Create your views here.

templates/base.html
<!doctype html>
<html  class="no-js" lang="en">
<!-- {# {% load compressed %} #} -->
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>SIMAS- Servicio de Información Mesoamericano sobre Agricultura Sostenible: Noticias</title>
    <meta name="title" content="SIMAS- Servicio de Información Mesoamericano sobre Agricultura Sostenible" />
    <meta name="description" content="Trabajamos por el respeto a la diversidad de la vida, el manejo transparente de nuestros recursos y relaciones internas y externas, la promoción de la equidad genérica y social y la re-valorización del conocimiento campesino e indígena como elementos fundamentales para la construcción de una nueva ciudadanía." />
    <meta name="keywords" content="desarrollo, humano, equidad de genero, conservación, gobernanza, recursos, naturales, soberanía, seguridad, alimentaria, empresas, rurales, servicios locales,  información, comunicación" />
    <meta name="author" content="SIMAS">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="shortcut icon" href="/static/img/favicon.ico" />
    <link rel="stylesheet" href="/static/css/normalize.css">
    <link rel="stylesheet" href="/static/css/foundation.css">
    <link rel="stylesheet" href="/static/css/animate.css">
    <link rel="stylesheet" href="/static/css/shadowbox.css">
    <link href="/static/css/ihover.css" rel="stylesheet">
    <link rel="stylesheet" href="/static/css/camera.css">
     <link href="//netdna.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
    <link rel="stylesheet" href="/static/css/simas.css">
    <link rel="stylesheet" href="/static/css/style_media.css">
    <link rel="stylesheet" href="/static/css/jquery.sidr.dark.css">
    <link href='http://fonts.googleapis.com/css?family=Roboto' rel='stylesheet' type='text/css'>


    {% if nota %}
    <meta property="og:title" content="{{nota.noticia}}" />
    <meta property="og:type" content="article" />
    <meta property="og:image" content="http://simas.org.ni/media/{{nota.foto}}">
    <meta property="og:image:width" content="300" />
    <meta property="og:image:height" content="300" />
    <meta property="og:description" content="{{nota.descripcion}}" />
    <meta property="og:url" content="http://simas.org.ni{{request.path}}" />
    <meta property="og:locale" content="es_ES" />
    {% endif %}
    {% block social %}{% endblock social %}
    <script src="/static/js/vendor/modernizr.js"></script>
    <script src="/static/js/vendor/jquery.js"></script>
    <script src="/static/js/shadowbox.js"></script>
    <script src="https://apis.google.com/js/platform.js" async defer>
    {lang: 'es'}
    </script>

    <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
    <script>
      (adsbygoogle = window.adsbygoogle || []).push({
        google_ad_client: "ca-pub-3709970567350271",
        enable_page_level_ads: true
      });
    </script>

      <script type="text/javascript">
      Shadowbox.init();
      </script>
      <script>
         (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
         (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
         m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
         })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

         ga('create', 'UA-76105558-1', 'auto');
         ga('send', 'pageview');

       </script>

</head>
<body>
  <header role="main" class="top">
      <div class="row">
          <div class="logo large-2 medium-2 columns">
              <a href="/"><img height="60" width="60" src="/static/img/logosimas.png" alt="Simas" title="Simas"></a>
          </div>
          <nav class="large-8 medium-8 columns">
              <ul class="menu">
                <li><a class="menu1" href="/quienes-somos/">QUIÉNES SOMOS</a></li>
                <li><a class="menu4" href="/noticias/">NOTICIAS</a></li>
                 <li><a class="menu5" href="/blogs/">BLOGS</a></li>
                <li><a class="menu2" href="/publicaciones/">PUBLICACIONES</a></li>
                <li><a class="menu3" href="/portafolio/sistemas">PORTAFOLIO</a></li>
                <li><a class="menu6" href="/contactenos/">CONTÁCTENOS</a></li>
              </ul>
          </nav>


      </div>
  </header>


  <div id="mobile-header">
    <a id="simple-menu" href="#sidr"><i class="fa fa-bars fa-2x"><span>Menu</span></i></a>
  </div>

  <div id="sidr">
    <a href="/"><img src="/static/img/logosimas.png" width="67" height="67"/></a>
    <ul>
      <li><a href="/quienes-somos/">QUIÉNES SOMOS</a></li>
      <li><a href="/noticias/">NOTICIAS</a></li>
       <li><a href="/blogs/">BLOGS</a></li>
      <li><a href="/publicaciones/">PUBLICACIONES</a></li>
      <li><a href="/portafolio/sistemas">PORTAFOLIO</a></li>
      <li><a href="/contactenos/">CONTÁCTENOS</a></li>
    </ul>
  </div>

<div class="wrapper">
  {% block contenido %}{% endblock contenido %}
</div>
    <script type="text/javascript">
        /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
        //var disqus_developer = 1; // this would set it to developer mode
        var disqus_shortname = 'simasni'; // required: replace example with your forum shortname

        /* * * DON'T EDIT BELOW THIS LINE * * */
        (function() {
            var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
            dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
            (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
        })();
    </script>

    <script src="/static/js/vendor/jquery.js"></script>
    <script src="/static/js/foundation.min.js"></script>
    <script src="http://cdn.jsdelivr.net/jquery.mixitup/latest/jquery.mixitup.min.js"></script>
    <script type='text/javascript' src='/static/js/jquery.easing.1.3.js'></script>
    <script type='text/javascript' src='/static/js/camera.js'></script>
    <script type='text/javascript' src="/static/js/jquery.sidr.js"></script>
    <script type='text/javascript' src="/static/js/core.js"></script>
    <script src="/static/js/wow.min.js"></script>
    <script type='text/javascript'>
      $(document).foundation();

      try{document.getElementsByName('googleSearchFrame')[0].height=1058;}catch(e){}
      $(document).ready(function() {
          $('#simple-menu').sidr();

        });


    </script>

    <script>
      new WOW().init();
    </script>

    {% block extra_js %}{% endblock extra_js %}

</body>
</html>

templates/busquedaSitio.html
<section class="search" role="search">
    <form id="cref" action="{% url 'googlesearch-results' %}">
      <input type="hidden" name="cref" value="http://simas.org.ni/busqueda/cref-cse.xml/" />
      <input type="hidden" name="cof" value="FORID:9" />
      <input id="search-input" type="text" role="search" value="Buscar..." name="q" id="q" onblur="if (this.value == '') { this.value = 'Buscar...';}" onfocus="if (this.value == 'Buscar...'){this.value = '';}" placeholder="Buscar...">
        <label for="search-input" class="ui-search"></label>
    </form>
</section>

templates/contacto.html
{% extends "base.html" %}

{% load thumbnail %}
{% load staticfiles %}

{% block extra_js %}
<link rel="stylesheet" href="{% static 'css/alertify.core.css' %}" />
<link rel="stylesheet" href="{% static 'css/alertify.default.css' %}" />
<script src="{% static 'js/alertify.js' %}"></script>
<script type="text/javascript">
	$('.menu a.menu6').addClass('activate');
	$(document).ready(function($) {


    $('#pony_form').on("submit", function(e){
        e.preventDefault();
        $.post("{% url 'contacto_ajax' %}", $("#pony_form").serialize(),
          function(data) {
            //data = eval('('+data+')');
            if ("exito" == data){
                  $('#pony_form')[0].reset();

                  $.getJSON('/captcha/refresh/', {}, function(json) {
                  $('.captcha').attr('src', json.image_url);
                  $('#id_captcha_0').val(json.key);
                  $('#id_captcha_1').val('');
                  });

                   alertify.success("Se ha enviado con exito su mensaje gracias.");
                }else{
                    alertify.error("Ocurrieron error lo lamentamos vuelva a intentar o refresque la pagina");
                }
      });
  });

    $('.js-captcha-refresh').click(function(){
    $form = $(this).parents('form');

    $.getJSON($(this).data('url'), {}, function(json) {
        // This your should update captcha image src and captcha hidden input
    });return false;
});
 
 });
	
</script>
	
{% endblock extra_js %}

{% block contenido %}

<style type="text/css">
	.google-maps {
        position: relative;
        padding-bottom: 87%;
        height: 0;
        overflow: hidden;
    }
    .google-maps iframe {
        position: absolute;
        top: 0;
        left: 0;
        width: 100% !important;
        height: 100% !important;
    }

</style>
<div class="quienesfondo">
  <img src="/media/{{foto_contacto.foto}}" alt="">
  <div class="row"><h1 class="text-center texto wow bounceInRight" data-wow-duration="2s">{{foto_contacto.titulo}}</h1></div>
</div>
<br><br>
<div class="row informacion">
  	<h2 class="text-center">Contacto institucional</h2>
    <p class="text-center">{{ contacto.texto|safe }}</p>   
</div>
<br>
<div id="FondoU">
{% for a in ubicacion_trabajador %}
	<div class="row todoContacto">
	  	<h2>{{a.ubicacion}}</h2>
	  	<hr>
	  	<ul class="small-12 columns medium-block-grid-3 large-block-grid-4">
	  	{% for b in personal %}
		  	{% if b.ubicacion.id == a.id %}
			  	<li>
				  	<!-- normal -->
			    	<div class="ih-item circle effect3 bottom_to_top"><a href="#">
			    	{% if b.foto %}
			    		{% thumbnail b.foto "300x300" crop="10%" as img %}
			    			<div class="img"><img src="/media/{{img}}" alt="img"></div>
			    		{% endthumbnail%}
			    	{% else %}
			    		<div class="img"><img src="/static/img/8.jpg" alt="img"></div>
			    	{% endif %}
				        
				        <div class="info">
				          <h3>{{b.nombres}}</h3>
				          <p>{{b.cargo}} / {{b.correo}}</p>
				        </div></a>
			    	</div>
			    	<!-- end normal -->
				 </li>
			{% endif %}
		{% endfor %}
		</ul>
    
	</div>
{% endfor %}
</div>

<div class="row contactos">
  	<h2 class="text-center">CONTÁCTENOS</h2>
  	<hr>
  	<div class="medium-6 large-6 columns">
  		<form id="pony_form" method="POST" class='form-horizontal' >{% csrf_token %}
      {% for field in form_contact %}
        <div class='control-group{% if field.errors %} error{% endif %}'>
            <label class='control-label' for='{{ field.auto_id }}'>{{ field.label }}</label>
            <div class='control'>
            {{ field }}
            {% for error in field.errors %}
            <span class='help-inline'>{{ error }}</span>
            {% endfor %}
            </div>
        </div> 
      {% endfor %}
    <div class='form-actions'>
        <input type="submit" class="tiny submit button" value="Enviar" />
    </div>
    </form>
  	</div>
  	<div class="medium-6 large-6 columns">
  		<div class="google-maps">
  			<iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d3900.5446344594784!2d-86.2861944!3d12.143278!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x8f71567744e12775%3A0xf45add63e22dd040!2sSIMAS!5e0!3m2!1ses-419!2s!4v1405466350955" width="600" height="450" frameborder="0" style="border:0"></iframe>
  		</div>
  	</div>

     
</div>

<hr>
{% include "footer.html" %}

{% endblock contenido %}

templates/index.html
{% extends "base.html" %}
{% load thumbnail %}
{% load staticfiles %}
{% block extra_js %}
<link rel="stylesheet" href="{% static 'css/flexslider.css' %}">
<script type="text/javascript" src="{% static 'js/jquery.flexslider.js' %}"></script>
<script type='text/javascript'> 
    
      $(document).ready(function(){
        $(function(){
          $('#camera_wrap_1').camera({
              height: '40%',
              playPause: false,
              pauseOnClick: false,
              pagination: false,
              hover: false,
              overlayer: false,
              imagePath: '/media/',
              time: 4000,
            });

        });

        $('.flexslider').flexslider({
            animation: "slide",
            animationLoop: true,
            slideshow: true,
            itemWidth: 200,
            itemMargin: 5,
            minItems: 2,
            maxItems:4,
            controlNav: false,
            directionNav: true,          
            prevText: "Previous",         
            nextText: "Next",
          });

    });
</script>
{% endblock extra_js %}

{% block contenido %}
<!-- Inicia el slider -->

<div class="home-slider">
    
  <div class="fluid_container">
    <div class="camera_wrap camera_emboss pattern_1" id="camera_wrap_1">
      {% for portada in latest_portada %}
        <div data-src="/media/{{portada.foto}}"> 
          <div id="frase1" class="animated slideInLeft">{{portada.texto1}}</div>
          <div id="frase2" class="animated slideInRight">{{portada.texto2}}</div>
        </div>
      {% endfor %}    
    </div><!-- #camera_wrap_4 -->
  </div><!-- .fluid_container -->
</div> <!-- finaliza el row del slider -->

<!-- inicia el buscador y redes sociales -->
<div class="cta-bar">
  <div class="row">

      <div class="large-4 medium-4 columns">
          <section class="social-icons">
              <ul>
                   <li class="youtube"><a href="https://www.youtube.com/user/simasnicaragua" target="_blank"></a></li>
                  <li class="twitter"><a href="https://twitter.com/simasnicaragua" target="_blank"></a></li>
                  <li class="facebook"><a href="https://www.facebook.com/simas.org.ni" target="_blank"></a></li>
                  <li class="google"><a href="https://plus.google.com/u/0/114100385731830799998/posts" target="_blank"></a></li>
              </ul>
          </section>
      </div>
  </div>
</div>
<!-- finaliza el buscador y la red social -->

<!-- inicia noticias -->
<div id="content" class="clearfix">
  <div class="news section">
    <div class="row">
      <div class="large-12 columns moverVer">
        <h2 class="section-title">Noticias</h2>
        <a class="right all" href="/noticias">VER TODAS </a>
      </div>   
        {% for obj in latest_news %}

        <div class="large-4 medium-4 columns">
          <article class="item">
              <figure>
                {% if obj.foto %}
                {% thumbnail obj.foto "300x190" crop="10%" as img %}
                  
                   <a href="{% url 'noticias:detalle-noticia' obj.id obj.uri %}"><img src="/media/{{img}}" alt="obj.noticia"></a>
                    
                 
                {% endthumbnail %}
                {% else %}
                <a href="{% url 'noticias:detalle-noticia' obj.id obj.uri %}"><img src="/static/img/sinImagen.png" alt="obj.publicacion"></a>
                {% endif %}
                  <figcaption>
                    <a href="{% url 'noticias:detalle-noticia' obj.id obj.uri %}">
                    <h3>{{obj.noticia|truncatewords:14}}</h3></a><br>
                     <p>{{obj.descripcion|safe}}</p>
                  </figcaption>
              </figure>
              <div class="meta">
                                                
                  <h6>{{obj.fecha|date:"m.d.y"}} / <a href="{% url 'noticias:detalle-noticia' obj.id obj.uri %}">LEER M&aacute;s &raquo;</a></h6>
              </div>
          </article>
        </div>
        
        {% endfor %}
     </div>
  </div> 
<!-- finaliza la parte de las noticias -->

<!-- Inicia parte de las publicaciones -->
<div class="release section">
  <div class="row">
    <br><br>
    <div class="large-12 columns moverVer">
      <h2 class="section-title">Publicaciones</h2>
      <a class="right all" href="/publicaciones">VER TODAS</a>
    </div>
    <ul class="small-block-grid-2 medium-block-grid-3 large-block-grid-4">
      {% for obj in latest_pub %}
      <li>
        <article class="pbn">
            <figure>
                <a href="{% url 'publicaciones:detalle-publicacion' obj.id obj.uri %}">
                    <div class="mask">
                        <h3>{{obj.publicacion}}</h3>
                    </div>
                    {% if obj.portada %}
                    {% thumbnail obj.portada "202x200" crop="10%" as img %} 
                      <img src="/media/{{img}}" alt="{{obj.publicacion}}">
                    {% endthumbnail %}
                    {% else %}
                      <img src="http://placehold.it/202x200" alt="{{obj.publicacion}}">
                    {% endif %}
                </a>
            </figure>
        </article>
     </li>
      {% endfor %}
      </ul>
  </div>
</div> 
<!-- Fin de la parte de las publicaciones -->

<!-- Inicia parte de quienes somos -->
<div class="fullbg section">
  <div class="row">
      <div class="large-9 large-centered columns">
          <h2>SIMAS aborda la innovaci&oacute;n de la agricultura sostenible con un enfoque amplio</h2>
          <a href="/historia-simas" class="button radius">Historia</a>
      </div>
  </div>
</div>
<!-- finaliza la parte de quienes somos -->
<!-- Inicia parte de los blogs -->
<div class="extras section">
<div class="row">
  <!-- solo blogs -->
  <div id="blogs" class="large-6 medium-6 columns">
    <h2 class="section-title">Blogs</h2>
    {% for blog in latest_blogs %}
      <article class="post">
        {% if blog.foto %}
          {% thumbnail blog.foto "140x100" crop="10%" as img %}
          <div class="post-thumb">
            <a href="{% url 'blogs:detalle-blog' blog.id blog.uri %}"><img src="/media/{{img}}" alt="{{blog.blog}}" /></a>
          </div> 
          {% endthumbnail %}
        {%else%}
          <a href="{% url 'blogs:detalle-blog' blog.id blog.uri %}"><img src="http://lorempixel.com/140/100/" alt=""></a>
        {% endif %}
        <div class="post-content">
            <div class="post-meta">
                <h6>{{blog.fecha|date:"m.d.y"}} / <span class="tag">{{blog.idcatblog}}</span></h6>
            </div>
            <a href="{% url 'blogs:detalle-blog' blog.id blog.uri %}"><h4>{{blog.blog}}</h4></a>
            <a href="{% url 'blogs:detalle-blog' blog.id blog.uri %}" class="more">Leer Art&iacute;culo &raquo;</a>
        </div>
      </article>
    {% endfor %}
  </div> <!-- fin parte solo blogs -->
  <!-- Inicia parte de los productos y servicios -->

  <div class="large-6 medium-6 columns" id="serv">
    <h2 class="section-title" >Servicios</h2>
    {% for porta in latest_service %}
      <div class="row">
              {% if porta.imagen%}
        
          <div class="large-4 medium-4 columns">
            <img src="/media/{{porta.imagen}}" alt="" width="80%" />
          </div>   
        
        {%else%}
            <div class="large-4 medium-4 columns">
              <img src="http://placehold.it/120x120" alt="" width="80%" />
            </div>
        {% endif %}
        <div class="product-content large-8 medium-8 columns">
          <a href="/portafolio/sistemas"><h4>{{porta.servicio}}</h4></a>
          <p>{{porta.descripcion|safe|truncatewords:10}}</p>
      </div>
      
      </div>
      <hr id="hrp">
    {% endfor %}
     <a href="/portafolio/sistemas" class="more">Ver más >></a>
  </div>
<!--  <div class="large-6 medium-6 columns" style="padding-bottom:1em !important">
    <div id="productos">
    <h2 class="section-title" >Servicios</h2>
    {% for porta in latest_service %}
    <div class="product">
      {% if porta.imagen%}
        {% thumbnail porta.imagen "120x120" crop="10%" as img %}
          <div class="product-thumb large-4 medium-4 columns">
            <img src="/media/{{porta.imagen}}" alt="" />
          </div>   
        {% endthumbnail %}
        {%else%}
            <div class="product-thumb large-4 medium-4 columns">
              <img src="http://placehold.it/120x120" alt="" />
            </div>
        {% endif %}
      <div class="product-content large-8 medium-8 columns">
          <h4>{{porta.servicio}}</h4>
          <p>{{porta.descripcion|safe|truncatewords:10}}</p>
      </div>
    </div>
    <hr id="hrp">
    {% endfor %}
    <a href="/portafolio/servicios">Ver más</a>
    </div>
  </div> --> <!-- finaliza parte solo de los productos y servicios -->
</div>
</div>
<!-- fin parte de blogs y servicios -->

<!-- inicia parte de las Alianzas -->
<div class="alianzas section">
    <div class="row">
        <div class="large-3 medium-3 columns">
            <h3>Alianzas</h3>
            <p>Estas son las organizaciones con las que trabajamos.</p>
            <!-- <a href="#" class="all">Ver todas</a> -->
        </div>
        <div class="large-1 medium-1 columns"></div>
        <div class="large-8 medium-8 columns">
          <div class="flexslider">
            <ul class="slides">
              {% for aliado in latest_aliados %}
              <li>
                  <a href="{{aliado.web}}" target="_blank">
                    {% thumbnail aliado.logo "120" crop="10%" format="PNG" as img %}
                      <img src="/media/{{img}}" alt="{{aliado.aliado}}" width="50%" style="margin:0 auto">
                    {% endthumbnail%}</a>
                </li>
              {% endfor %}
            </ul>
          </div>
        </div>
    </div>
</div>
<!-- fin de la parte de las alianza -->
</div> <!-- fin del content -->
{% include "footer.html" %}

{% endblock contenido %}

templates/paginacion.html
<ul class="pagination">
{% if page_obj.has_previous %}
  <li class="arrow unavailable"><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
{% endif %}
{% for page in page_numbers %}
  {% if page %}
    {% ifequal page page_obj.number %}
      <li class="current">{{ page }}</li>
    {% else %}
      <li><a href="?page={{ page }}">{{ page }}</a></li>
    {% endifequal %}
  {% else %}
    <li>...</li> 
  {% endif %}
{% endfor %}
{% if page_obj.has_next %}
  <li class="arrow"><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
{% endif %}
</ul>